CREATE TABLE s_product
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    price  DECIMAL,
    image  VARCHAR(255),
    weight DECIMAL,
    CONSTRAINT pk_s_product PRIMARY KEY (id)
);

CREATE TABLE s_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone    VARCHAR(255)                            NOT NULL,
    age      INTEGER,
    username VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_s_user PRIMARY KEY (id)
);

ALTER TABLE s_user
    ADD CONSTRAINT uc_s_user_phone UNIQUE (phone);

ALTER TABLE s_user
    ADD CONSTRAINT uc_s_user_username UNIQUE (username);


CREATE TABLE s_position
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    count      INTEGER,
    CONSTRAINT pk_s_position PRIMARY KEY (id)
);

ALTER TABLE s_position
    ADD CONSTRAINT FK_S_POSITION_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES s_product (id);


