CREATE TABLE s_product
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    price  DECIMAL,
    image  VARCHAR(255),
    weight DECIMAL,
    CONSTRAINT pk_s_product PRIMARY KEY (id)
);